[package]
name = "ruuvitag-listener"
description = "Print RuuviTag measurements in Telegraf compatible format"
version = "0.3.10"
license = "MIT"
authors = ["Ville Lautanala <lautis@gmail.com>"]
repository = "https://github.com/lautis/ruuvitag-listener"
keywords = ["ruuvi", "ruuvitag", "telegraf"]
edition = "2018"

[dependencies]
rumble = { git = "https://github.com/lautis/rumble", tag = "v0.3.0.ruuvitag-listener.2" }
ruuvi-sensor-protocol = "0.3.*"
structopt = { version = "0.2", default-features = false }

[profile.release]
opt-level = "s"
lto = true
panic = "abort"
