[package]
name = "ruuvitag-listener"
description = "Listen to RuuviTag measurements and output in Telegraf compatible format"
version = "0.1.1"
license = "MIT"
authors = ["Ville Lautanala <lautis@gmail.com>"]
repository = "https://github.com/lautis/ruuvitag-listener"
keywords = ["ruuvi", "ruuvitag", "telegraf"]

[dependencies]
rumble = "0.3.*"
ruuvi-sensor-protocol = "0.2.*"

[profile.release]
opt-level = "s"
lto = true
