[package]
name = "ruuvitag-listener"
description = "Print RuuviTag measurements in Telegraf compatible format"
version = "0.3.1-alpha.0"
license = "MIT"
authors = ["Ville Lautanala <lautis@gmail.com>"]
repository = "https://github.com/lautis/ruuvitag-listener"
keywords = ["ruuvi", "ruuvitag", "telegraf"]

[dependencies]
rumble = "0.3.*"
ruuvi-sensor-protocol = "0.2.*"
structopt = { version = "0.2", default-features = false }

[profile.release]
opt-level = "s"
lto = true
