[package]
name = "ruuvitag-listener"
description = "Print RuuviTag measurements in Telegraf compatible format"
version = "0.3.4"
license = "MIT"
authors = ["Ville Lautanala <lautis@gmail.com>"]
repository = "https://github.com/lautis/ruuvitag-listener"
keywords = ["ruuvi", "ruuvitag", "telegraf"]

[dependencies]
rumble = { git = "https://github.com/lautis/rumble", tag = "v0.3.0.ruuvitag-listener.1" }
ruuvi-sensor-protocol = "0.2.*"
structopt = { version = "0.2", default-features = false }

[profile.release]
opt-level = "s"
lto = true
panic = "abort"
